repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  # Standard checks
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
    exclude: ^charts/[^/]+/templates/
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]

  # Cross platform
  - id: check-case-conflict
  - id: destroyed-symlinks
  - id: mixed-line-ending
    args: [--fix=lf]

  # Security
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
  - id: detect-private-key

  # Git
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: forbid-submodules

  # Python
  - id: check-docstring-first
  - id: debug-statements
  - id: name-tests-test
  - id: requirements-txt-fixer

- repo: https://github.com/google/yamlfmt
  rev: v0.14.0
  hooks:
  - id: yamlfmt
    exclude: ^istari-platform/[^/]+/templates/
    args:
    - '-formatter=indentless_arrays=true'
    - '-formatter=pad_line_comments=2'
    - '-formatter=retain_line_breaks=true'

- repo: local
  hooks:
  - id: yaml-extension
    name: Check if YAML files use *.yaml extension.
    entry: YAML filenames must have .yaml extension.
    language: fail
    files: '.yml$'

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.24
  hooks:
  - id: helmlint

- repo: https://github.com/norwoodj/helm-docs
  rev: v1.14.2
  hooks:
  - id: helm-docs
    args:
    # Make the tool search for charts only under the `charts` directory
    - --chart-search-root=.
