{{- $serviceValues := .Values.magicDocs -}}
{{- if $serviceValues.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "magic-docs.fullname" . | quote }}
  labels:
    {{- include "magic-docs.labels" . | nindent 4 }}
  {{- with $serviceValues.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $serviceValues.serviceType | quote }}
  ports:
  - name: "http"
    port: 80
    targetPort: "http"
    protocol: "TCP"
  selector:
    {{- include "magic-docs.selectorLabels" . | nindent 4 }}
{{- end }}
