name: pre-commit Checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    types:
    - opened
    - ready_for_review
    - reopened
    - synchronize

env:
  python_version: '3.12'
  helm_docs_version: '1.14.2'  # https://github.com/norwoodj/helm-docs/releases

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5  # Also sets 'env.pythonLocation'
      with:
        python-version: ${{ env.python_version }}

    - uses: azure/setup-helm@v4
      id: install_helm
      # with:
      #   version: '<version>' # default is latest (stable)

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2

    - name: Install Helm Docs
      uses: envoy/install-helm-docs@v1.0.0
      with:
        # Helm Docs Version to install (Mandatory)
        version: ${{ env.helm_docs_version }}

    # Based on: https://github.com/pre-commit/action/blob/0dbc303468d9ee1ae3a4cddd9b697c1424c73522/action.yml
    - name: Install pre-commit
      run: python -m pip install pre-commit
      shell: bash
    - run: python -m pip freeze --local
      shell: bash
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ runner.os }}|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
